name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build getting-started
      working-directory: ./getting-started/hello
      run: go build -v ./...

    - name: Test getting-started
      working-directory: ./getting-started/greetings
      run: go test -v ./...

    - name: Build data-access
      working-directory: ./data-access
      run: go build -v ./...

    - name: Build web-service-gin
      working-directory: ./web-service-gin
      run: go build -v ./...
